# Generated by Django 2.0.5 on 2018-05-26 23:46

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='image/article/', verbose_name='文章封面'),
        ),
    ]
