# Generated by Django 2.0.5 on 2018-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180620_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='能否删除'),
        ),
    ]
