# Generated by Django 2.0.5 on 2018-05-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='图片地址')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='图片名称')),
                ('describe', models.CharField(max_length=200, null=True, verbose_name='图片描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='图片创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='图片更新时间')),
            ],
            options={
                'verbose_name': '图库',
                'verbose_name_plural': '图库',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, null=True, verbose_name='相册名称')),
                ('type_describe', models.CharField(max_length=200, null=True, verbose_name='相册类型介绍')),
                ('type_image', models.ImageField(upload_to='image/type/', verbose_name='相册封面')),
            ],
            options={
                'verbose_name': '相册类型',
                'verbose_name_plural': '相册类型',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='img_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.ImageType', verbose_name='所属类型'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属人'),
        ),
    ]
