# Generated by Django 2.0.5 on 2018-05-26 23:09

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='images/', verbose_name='图片地址'),
        ),
    ]
